FROM postgres:9.6-alpine

ENV \
  POSTGRES_PASSWORD=ER0TVseBNiHetBGM \
  BARMAN_USER=barman \
  BARMAN_PASSWORD=KekKbctxiSzQzVn9 \
  BARMAN_SLOT_NAME=barman \
  STREAMING_USER=streaming_barman \
  STREAMING_PASSWORD=CQzJH3gHSgdlfSkW \
  PGDATA=/pgdata

VOLUME $PGDATA

ADD repos.txt /tmp/

RUN cat /tmp/repos.txt >> /etc/apk/repositories && \
    rm /tmp/repos.txt && \
    apk --update --upgrade add gosu@testing supervisor && \
    mkdir -p /var/log/supervisor/postgres && \
    chown -R postgres:postgres $PGDATA /var/log/supervisor/postgres

ADD supervisord.conf /etc/
ADD postgresql.conf.dockerized /usr/local/share/postgresql
ADD pg_hba.conf.dockerized /usr/local/share/postgresql

EXPOSE 5432

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["supervisord", "-c", "/etc/supervisord.conf"]
